/**
 * exporter.js
 * Exports stencil layers to SVG, PNG, PDF, and EPS formats.
 */

// ---- Registration mark helpers ----

/**
 * Build SVG path data for a single registration mark (crosshair + circle).
 * @param {number} cx
 * @param {number} cy
 * @param {number} r   - radius
 * @returns {string}
 */
function regMarkPath(cx, cy, r) {
  return [
    `M ${cx - r} ${cy} L ${cx + r} ${cy}`,      // horizontal bar
    `M ${cx} ${cy - r} L ${cx} ${cy + r}`,      // vertical bar
    `M ${cx + r} ${cy} A ${r} ${r} 0 1 0 ${cx - r} ${cy} A ${r} ${r} 0 1 0 ${cx + r} ${cy}`, // circle
  ].join(' ');
}

/**
 * Return SVG <path> elements for the 4 corner registration marks.
 * @param {number} width
 * @param {number} height
 * @param {number} margin
 * @returns {string}
 */
function registrationMarks(width, height, margin = 20) {
  const r = 8;
  const marks = [
    [margin,         margin],
    [width - margin, margin],
    [margin,         height - margin],
    [width - margin, height - margin],
  ];

  return marks.map(([cx, cy]) =>
    `<path d="${regMarkPath(cx, cy, r)}" stroke="#000" stroke-width="0.8" fill="none" />`
  ).join('\n');
}

// ---- SVG export ----

/**
 * Build a complete SVG document for one or more layers.
 * @param {import('./pipeline.js').Layer[]} layers
 * @param {object} opts
 * @returns {string} SVG source
 */
export function buildSVG(layers, opts = {}) {
  const {
    includeRegMarks = true,
    includeColorFill = true,
    bwMode = false,
    width  = layers[0]?.metadata.width  ?? 800,
    height = layers[0]?.metadata.height ?? 600,
  } = opts;

  const pathEls = layers
    .filter(l => l.visible !== false)
    .map(l => {
      const fillColor = bwMode
        ? '#000000'
        : (includeColorFill ? l.color : 'none');
      const strokeColor = bwMode ? '#000000' : l.color;
      const opacity = l.opacity ?? 1;

      return `  <path
    id="${escapeAttr(l.id)}"
    data-layer="${escapeAttr(l.name)}"
    d="${l.pathData}"
    fill="${escapeAttr(fillColor)}"
    stroke="${escapeAttr(strokeColor)}"
    stroke-width="0.5"
    opacity="${opacity}"
  />`;
    })
    .join('\n');

  const regEl = includeRegMarks ? registrationMarks(width, height) : '';

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg"
     width="${width}" height="${height}"
     viewBox="0 0 ${width} ${height}">
  <title>Stencil Export</title>
  <!-- Generated by StencilGen -->
${pathEls}
${regEl}
</svg>`;
}

/**
 * Trigger a browser download of a text file.
 * @param {string} content
 * @param {string} filename
 * @param {string} mime
 */
function downloadText(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Export layers as SVG.
 * @param {import('./pipeline.js').Layer[]} layers
 * @param {object} opts
 */
export function exportSVG(layers, opts = {}) {
  const svg = buildSVG(layers, opts);
  downloadText(svg, 'stencil.svg', 'image/svg+xml');
}

// ---- PNG export ----

/**
 * Render layers onto a canvas and return it.
 * @param {import('./pipeline.js').Layer[]} layers
 * @param {object} opts
 * @returns {HTMLCanvasElement}
 */
function renderToCanvas(layers, opts = {}) {
  const {
    width      = layers[0]?.metadata.width  ?? 800,
    height     = layers[0]?.metadata.height ?? 600,
    background = 'transparent',
    bwMode     = false,
    dpi        = 96,
  } = opts;

  // DPI scaling: 96 dpi = 1x, 300 dpi ≈ 3.125x
  const scale = dpi / 96;
  const pw    = Math.round(width  * scale);
  const ph    = Math.round(height * scale);

  const canvas = document.createElement('canvas');
  canvas.width  = pw;
  canvas.height = ph;

  const ctx = canvas.getContext('2d');

  if (background === 'white') {
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, pw, ph);
  }

  ctx.scale(scale, scale);

  for (const layer of layers) {
    if (!layer.visible) continue;

    // Draw the preview bitmap tinted
    const offscreen = document.createElement('canvas');
    offscreen.width  = width;
    offscreen.height = height;
    const octx = offscreen.getContext('2d');
    octx.putImageData(layer.previewBitmap, 0, 0);

    if (bwMode) {
      octx.globalCompositeOperation = 'source-in';
      octx.fillStyle = '#000000';
      octx.fillRect(0, 0, width, height);
    }

    ctx.globalAlpha = layer.opacity ?? 1;
    ctx.drawImage(offscreen, 0, 0);
    ctx.globalAlpha = 1;
  }

  return canvas;
}

/**
 * Export layers as PNG.
 * @param {import('./pipeline.js').Layer[]} layers
 * @param {object} opts
 */
export function exportPNG(layers, opts = {}) {
  const canvas = renderToCanvas(layers, opts);
  canvas.toBlob(blob => {
    const url = URL.createObjectURL(blob);
    const a   = Object.assign(document.createElement('a'), { href: url, download: 'stencil.png' });
    a.click();
    URL.revokeObjectURL(url);
  }, 'image/png');
}

// ---- PDF export ----

/**
 * Build a minimal valid PDF that contains an SVG image rendered via a page
 * with an embedded SVG (encoded in an XObject as plain text streams).
 *
 * For maximum compatibility we use a simple PDF 1.4 structure with the SVG
 * content embedded as a plain text stream.  This is then opened as a
 * one-page PDF in any viewer.
 *
 * @param {import('./pipeline.js').Layer[]} layers
 * @param {object} opts
 * @returns {Uint8Array}
 */
export function buildPDF(layers, opts = {}) {
  const svgContent = buildSVG(layers, opts);

  const {
    width  = layers[0]?.metadata.width  ?? 800,
    height = layers[0]?.metadata.height ?? 600,
  } = opts;

  // PDF uses points (1 pt = 1/72 inch).  We treat pixels as 72 dpi points.
  const ptW = width;
  const ptH = height;

  const enc = new TextEncoder();

  // We embed the SVG as a comment note inside the PDF so the file is still
  // valid, and render the content by including an SVG content stream
  // converted to a simple PDF content stream of filled rectangles per pixel.
  // For a proper vector PDF we use SVG-to-PDF conversion.

  // Simple approach: embed SVG data as an attachment and render a PNG
  // thumbnail as the page content.
  const canvas = renderToCanvas(layers, { ...opts, dpi: 72 });
  const pngDataURL = canvas.toDataURL('image/jpeg', 0.92); // JPEG for smaller size
  const base64Data = pngDataURL.split(',')[1];
  const imgBytes   = base64ToUint8Array(base64Data);
  const imgLen     = imgBytes.length;

  // Build PDF structure
  const parts = [];
  const offsets = [];

  const addObj = (content) => {
    offsets.push(parts.reduce((s, p) => s + p.length, 0));
    parts.push(enc.encode(content + '\n'));
  };

  // Header
  parts.push(enc.encode('%PDF-1.4\n%\xC7\xEC\x8F\xA2\n'));

  // Object 1: Catalog
  addObj('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj');

  // Object 2: Pages
  addObj('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj');

  // Object 3: Page
  addObj(`3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${ptW} ${ptH}] /Contents 4 0 R /Resources << /XObject << /Img 5 0 R >> >> >>\nendobj`);

  // Object 4: Content stream — draw image filling the page
  const contentStream = `q\n${ptW} 0 0 ${ptH} 0 0 cm\n/Img Do\nQ\n`;
  const csBytes = enc.encode(contentStream);
  addObj(`4 0 obj\n<< /Length ${csBytes.length} >>\nstream\n${contentStream}\nendstream\nendobj`);

  // Object 5: Image XObject
  const imgHeader = `5 0 obj\n<< /Type /XObject /Subtype /Image /Width ${canvas.width} /Height ${canvas.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${imgLen} >>\nstream\n`;
  const imgFooter = '\nendstream\nendobj\n';

  offsets.push(parts.reduce((s, p) => s + p.length, 0));
  parts.push(enc.encode(imgHeader));
  parts.push(imgBytes);
  parts.push(enc.encode(imgFooter));

  // Cross-reference table
  const xrefOffset = parts.reduce((s, p) => s + p.length, 0);
  const xrefCount  = offsets.length + 1; // +1 for object 0

  let xref = `xref\n0 ${xrefCount}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    xref += String(off).padStart(10, '0') + ' 00000 n \n';
  }

  parts.push(enc.encode(xref));

  // Trailer
  parts.push(enc.encode(
    `trailer\n<< /Size ${xrefCount} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`
  ));

  // Concatenate all parts
  const totalLen = parts.reduce((s, p) => s + p.length, 0);
  const result   = new Uint8Array(totalLen);
  let pos = 0;
  for (const p of parts) {
    result.set(p, pos);
    pos += p.length;
  }

  return result;
}

/**
 * Export layers as PDF.
 * @param {import('./pipeline.js').Layer[]} layers
 * @param {object} opts
 */
export function exportPDF(layers, opts = {}) {
  const pdf  = buildPDF(layers, opts);
  const blob = new Blob([pdf], { type: 'application/pdf' });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: 'stencil.pdf' });
  a.click();
  URL.revokeObjectURL(url);
}

// ---- EPS export ----

/**
 * Build a minimal EPS document from layers.
 * @param {import('./pipeline.js').Layer[]} layers
 * @param {object} opts
 * @returns {string}
 */
export function buildEPS(layers, opts = {}) {
  const {
    bwMode = false,
    width  = layers[0]?.metadata.width  ?? 800,
    height = layers[0]?.metadata.height ?? 600,
  } = opts;

  const lines = [
    '%!PS-Adobe-3.0 EPSF-3.0',
    `%%BoundingBox: 0 0 ${width} ${height}`,
    '%%Title: Stencil Export',
    '%%Creator: StencilGen',
    '%%EndComments',
    '',
    '% Setup',
    '1 setlinewidth',
    '',
  ];

  for (const layer of layers) {
    if (!layer.visible) continue;
    const [r, g, b] = hexToRGBNorm(bwMode ? '#000000' : layer.color);
    lines.push(`% Layer: ${layer.name}`);
    lines.push(`${r.toFixed(3)} ${g.toFixed(3)} ${b.toFixed(3)} setrgbcolor`);

    // Convert SVG path data to PostScript (simplified: M=moveto, L=lineto, Z=closepath)
    const ps = svgPathToPS(layer.pathData, height);
    lines.push(ps, 'fill', '');
  }

  lines.push('%%EOF');
  return lines.join('\n');
}

/**
 * Export layers as EPS.
 * @param {import('./pipeline.js').Layer[]} layers
 * @param {object} opts
 */
export function exportEPS(layers, opts = {}) {
  const eps = buildEPS(layers, opts);
  downloadText(eps, 'stencil.eps', 'application/postscript');
}

// ---- Export All (multi-format zip-like blob) ----

/**
 * Export all formats as separate downloads.
 * @param {import('./pipeline.js').Layer[]} layers
 * @param {object} opts
 */
export function exportAll(layers, opts = {}) {
  exportSVG(layers, opts);
  exportPNG(layers, { ...opts, background: 'white' });
  exportPDF(layers, opts);
}

// ---- Helpers ----

function escapeAttr(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function hexToRGBNorm(hex) {
  const clean = hex.replace('#', '');
  const val   = parseInt(clean, 16);
  return [
    ((val >> 16) & 0xff) / 255,
    ((val >> 8)  & 0xff) / 255,
     (val        & 0xff) / 255,
  ];
}

function base64ToUint8Array(base64) {
  const binary = atob(base64);
  const bytes  = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

/**
 * Very simplified SVG path → PostScript converter.
 * Handles M, L, Z commands only.
 * PostScript Y-axis is flipped relative to SVG.
 */
function svgPathToPS(pathData, svgHeight) {
  if (!pathData) return '';

  const tokens = pathData.split(/\s+/);
  const ps     = [];
  let   i      = 0;

  while (i < tokens.length) {
    const cmd = tokens[i++];
    switch (cmd) {
      case 'M': {
        const x =  parseFloat(tokens[i++]);
        const y = svgHeight - parseFloat(tokens[i++]);
        ps.push(`${x.toFixed(2)} ${y.toFixed(2)} moveto`);
        break;
      }
      case 'L': {
        const x =  parseFloat(tokens[i++]);
        const y = svgHeight - parseFloat(tokens[i++]);
        ps.push(`${x.toFixed(2)} ${y.toFixed(2)} lineto`);
        break;
      }
      case 'Z':
        ps.push('closepath');
        break;
      default:
        // Try to parse as implicit lineto
        if (!isNaN(parseFloat(cmd))) {
          const x =  parseFloat(cmd);
          const y = svgHeight - parseFloat(tokens[i++]);
          ps.push(`${x.toFixed(2)} ${y.toFixed(2)} lineto`);
        }
    }
  }

  return ps.join('\n');
}
